export const availableVehicles = [
  {
    serviceTypeCode: 'ALC',
    vehicles: [
      {
        code: '32',
        description: 'MINI COOPER CONVERTIBLE',
        doors: '2',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3050',
          feeType: 'Fee Total',
          calculatedDistance: '6',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '2410',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '215',
        description: 'BMW 520D SEDAN',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '6020',
          feeType: 'Fee Total',
          calculatedDistance: '12',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '5380',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '233',
        description: 'BMW X5 XDRIVE 30D',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '6410',
          feeType: 'Fee Total',
          calculatedDistance: '18',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '5770',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '263',
        description: 'BMW 730LD SEDAN',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '8140',
          feeType: 'Fee Total',
          calculatedDistance: '24',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '7500',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '288',
        description: 'BMW M4 COUPE',
        doors: '2',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '7860',
          feeType: 'Fee Total',
          calculatedDistance: '30',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '7220',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '293',
        description: 'BMW M4 CONVERTIBLE',
        doors: '2',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '7860',
          feeType: 'Fee Total',
          calculatedDistance: '36',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '7220',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '295',
        description: 'VOLKSWAGEN TIGUAN 2.0TSI 4 MOTION R-LINE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3380',
          feeType: 'Fee Total',
          calculatedDistance: '42',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '2740',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '306',
        description: 'MERCEDES BENZ V250 CDI 7 SEATER',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '6020',
          feeType: 'Fee Total',
          calculatedDistance: '48',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '5380',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '317',
        description: 'RANGE ROVER SPORT TDV6 SE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '8930',
          feeType: 'Fee Total',
          calculatedDistance: '54',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '8290',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '406',
        description: 'BMW X7 XDRIVE 30D',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '8930',
          feeType: 'Fee Total',
          calculatedDistance: '60',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '8290',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '450',
        description: 'VOLKSWAGEN POLO GTI',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '2880',
          feeType: 'Fee Total',
          calculatedDistance: '66',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '2240',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '455',
        description: 'BMW M8 COUPÉ',
        doors: '2',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '10660',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '10020',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '459',
        description: 'LAND ROVER DEFENDER 110 SD4 SE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '6070',
          feeType: 'Fee Total',
          calculatedDistance: '78',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '5430',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '460',
        description: 'LAND ROVER DISCOVERY 5 TD6 SE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '6070',
          feeType: 'Fee Total',
          calculatedDistance: '84',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '5430',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '461',
        description: 'VOLKSWAGEN T-ROC 2.0 TSI R-LINE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3050',
          feeType: 'Fee Total',
          calculatedDistance: '90',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '2410',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '468',
        description: 'AUDI TT RS COUPÉ',
        doors: '2',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '6520',
          feeType: 'Fee Total',
          calculatedDistance: '96',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '5880',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '469',
        description: 'MINI JOHN COOPER WORKS CLUBMAN',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '4000',
          feeType: 'Fee Total',
          calculatedDistance: '102',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '3360',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '470',
        description: 'BMW X4 XDRIVE 20D M SPORT',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '6070',
          feeType: 'Fee Total',
          calculatedDistance: '108',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '5430',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '479',
        description: 'BMW 750LI XDRIVE SEDAN',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '8140',
          feeType: 'Fee Total',
          calculatedDistance: '114',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '7500',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '480',
        description: 'BMW 740LI SEDAN',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '8140',
          feeType: 'Fee Total',
          calculatedDistance: '120',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '7500',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '483',
        description: 'BMW M4 COMPETITION COUPE G82',
        doors: '2',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '7860',
          feeType: 'Fee Total',
          calculatedDistance: '126',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '7220',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '484',
        description: 'VOLKSWAGEN GOLF 8 GTI',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3380',
          feeType: 'Fee Total',
          calculatedDistance: '132',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '2740',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '486',
        description: 'AUDI Q8 45TDI QUATTRO',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '7860',
          feeType: 'Fee Total',
          calculatedDistance: '138',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '7220',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '493',
        description: 'BMW M8 COMPETITION CONVERTIBLE',
        doors: '2',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '10660',
          feeType: 'Fee Total',
          calculatedDistance: '144',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '10020',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '494',
        description: 'MERCEDES BENZ V300D AVANTGARDE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '6520',
          feeType: 'Fee Total',
          calculatedDistance: '150',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '5880',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '496',
        description: 'AUDI Q7 45 TDI QUATTRO TIPTRONIC S LINE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '6410',
          feeType: 'Fee Total',
          calculatedDistance: '156',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '5770',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '497',
        description: 'BMW M2 COMPETITION COUPÉ',
        doors: '2',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '6020',
          feeType: 'Fee Total',
          calculatedDistance: '162',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '5380',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '499',
        description: 'BMW M850I XDRIVE COUPÉ',
        doors: '2',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '7860',
          feeType: 'Fee Total',
          calculatedDistance: '168',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '7220',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '501',
        description: 'MERCEDES BENZ GLE400D COUPÉ 4MATIC AMG LINE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '6410',
          feeType: 'Fee Total',
          calculatedDistance: '174',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '5770',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '502',
        description: 'MERCEDES BENZ AMG GLE63 S 4MATIC COUPÉ',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '10660',
          feeType: 'Fee Total',
          calculatedDistance: '180',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '10020',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '503',
        description: 'MERCEDES BENZ AMG G-CLASS G63',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '10660',
          feeType: 'Fee Total',
          calculatedDistance: '186',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '10020',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '504',
        description: 'BMW M8 COMPETITION GRAN COUPÉ',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '10660',
          feeType: 'Fee Total',
          calculatedDistance: '192',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '10020',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '505',
        description: 'BMW M8 COMPETITION COUPÉ',
        doors: '2',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '10660',
          feeType: 'Fee Total',
          calculatedDistance: '198',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '10020',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '506',
        description: 'MINI COOPER S COUNTRYMAN',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3380',
          feeType: 'Fee Total',
          calculatedDistance: '204',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '2740',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '508',
        description: 'BMW M3 COMPETITION M XDRIVE',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '8930',
          feeType: 'Fee Total',
          calculatedDistance: '210',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '8290',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '509',
        description: 'BMW X3 XDRIVE 20D',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3380',
          feeType: 'Fee Total',
          calculatedDistance: '216',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '2740',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '510',
        description: 'MERCEDES BENZ V220D AVANTGARDE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '4900',
          feeType: 'Fee Total',
          calculatedDistance: '222',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '4260',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '512',
        description: 'MERCEDES BENZ V300D EXCLUSIVE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '6520',
          feeType: 'Fee Total',
          calculatedDistance: '228',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '5880',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '514',
        description: 'MERCEDES BENZ C220D SEDAN AMG LINE',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3660',
          feeType: 'Fee Total',
          calculatedDistance: '234',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '3020',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '515',
        description: 'MERCEDES BENZ C220D SEDAN AVANTGARDE',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3660',
          feeType: 'Fee Total',
          calculatedDistance: '240',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '3020',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '516',
        description: 'MERCEDES BENZ C200 SEDAN AVANTGARDE',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3660',
          feeType: 'Fee Total',
          calculatedDistance: '246',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '3020',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '522',
        description: 'BMW X6 XDRIVE 30D',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '7860',
          feeType: 'Fee Total',
          calculatedDistance: '252',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '7220',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '526',
        description: 'MERCEDES BENZ C63 S COUPÉ AMG',
        doors: '2',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '8930',
          feeType: 'Fee Total',
          calculatedDistance: '258',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '8290',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '528',
        description: 'BMW M135I XDRIVE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '4000',
          feeType: 'Fee Total',
          calculatedDistance: '264',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '3360',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '534',
        description: 'BMW 420I CONVERTIBLE',
        doors: '2',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3660',
          feeType: 'Fee Total',
          calculatedDistance: '270',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '3020',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '535',
        description: 'BMW M4 COMPETITION CONVERTIBLE',
        doors: '2',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '7860',
          feeType: 'Fee Total',
          calculatedDistance: '276',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '7220',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '537',
        description: 'BMW M440I XDRIVE COUPÉ',
        doors: '2',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '6070',
          feeType: 'Fee Total',
          calculatedDistance: '282',
          calculatedTime: '0',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'C',
              price: '640',
              feeType: 'COLLECTION FEE',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'F',
              price: '1800',
              feeType: 'FUEL DEPOSIT',
              calculatedDistance: '31',
              calculatedTime: '2200',
            },
            {
              priceUnit: 'R',
              price: '5430',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
    ],
  },
  {
    serviceTypeCode: 'CDD',
    vehicles: [
      {
        code: '215',
        description: 'BMW 520D SEDAN',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3430',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '3430',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '233',
        description: 'BMW X5 XDRIVE 30D',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3730',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '3730',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '293',
        description: 'BMW M4 CONVERTIBLE',
        doors: '2',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '4315',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '4315',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '295',
        description: 'VOLKSWAGEN TIGUAN 2.0TSI 4 MOTION R-LINE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '2680',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '2680',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '306',
        description: 'MERCEDES BENZ V250 CDI 7 SEATER',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3430',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '3430',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '312',
        description: 'TOYOTA COROLLA QUEST 1.8 MANUAL',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '1490',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '1490',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '317',
        description: 'RANGE ROVER SPORT TDV6 SE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '4995',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '4995',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '319',
        description: 'TOYOTA RAV4 2.0 GX AUTO',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '1855',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '1855',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '406',
        description: 'BMW X7 XDRIVE 30D',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '4995',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '4995',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '459',
        description: 'LAND ROVER DEFENDER 110 SD4 SE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3730',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '3730',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '473',
        description: 'MERCEDES BENZ VITO 116 CDI TOURER SELECT LWB',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3155',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '3155',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '479',
        description: 'BMW 750LI XDRIVE SEDAN',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '4315',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '4315',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '484',
        description: 'VOLKSWAGEN GOLF 8 GTI',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '2680',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '2680',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '494',
        description: 'MERCEDES BENZ V300D AVANTGARDE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3730',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '3730',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '495',
        description: 'VOLKSWAGEN KOMBI 2.0 TDI',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3155',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '3155',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '496',
        description: 'AUDI Q7 45 TDI QUATTRO TIPTRONIC S LINE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3730',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '3730',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '501',
        description: 'MERCEDES BENZ GLE400D COUPÉ 4MATIC AMG LINE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3730',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '3730',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '514',
        description: 'MERCEDES BENZ C220D SEDAN AMG LINE',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '2990',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '2990',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '515',
        description: 'MERCEDES BENZ C220D SEDAN AVANTGARDE',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '2990',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '2990',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '516',
        description: 'MERCEDES BENZ C200 SEDAN AVANTGARDE',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '2990',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '2990',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '521',
        description: 'TOYOTA QUANTUM 2.8 LWB GL 11 SEATER',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3155',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '3155',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '532',
        description: 'MERCEDES BENZ SPRINTER 516CDI',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '4315',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '4315',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '533',
        description: 'TOYOTA URBAN CRUISER 1.5XS MT',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '1490',
          feeType: 'Fee Total',
          calculatedDistance: '35',
          calculatedTime: '2600',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '1490',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
    ],
  },
  {
    serviceTypeCode: 'CDT',
    vehicles: [
      {
        code: '215',
        description: 'BMW 520D SEDAN',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3430',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '3430',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '233',
        description: 'BMW X5 XDRIVE 30D',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3730',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '3730',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '293',
        description: 'BMW M4 CONVERTIBLE',
        doors: '2',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '4315',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '4315',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '295',
        description: 'VOLKSWAGEN TIGUAN 2.0TSI 4 MOTION R-LINE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '1165',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '1165',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '306',
        description: 'MERCEDES BENZ V250 CDI 7 SEATER',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3430',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '3430',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '312',
        description: 'TOYOTA COROLLA QUEST 1.8 MANUAL',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '735',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '735',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '317',
        description: 'RANGE ROVER SPORT TDV6 SE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '4995',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '4995',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '319',
        description: 'TOYOTA RAV4 2.0 GX AUTO',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '920',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '920',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '406',
        description: 'BMW X7 XDRIVE 30D',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '4995',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '4995',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '459',
        description: 'LAND ROVER DEFENDER 110 SD4 SE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3730',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '3730',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '473',
        description: 'MERCEDES BENZ VITO 116 CDI TOURER SELECT LWB',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '1820',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '1820',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '479',
        description: 'BMW 750LI XDRIVE SEDAN',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '4315',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '4315',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '484',
        description: 'VOLKSWAGEN GOLF 8 GTI',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '1165',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '1165',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '494',
        description: 'MERCEDES BENZ V300D AVANTGARDE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3730',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '3730',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '495',
        description: 'VOLKSWAGEN KOMBI 2.0 TDI',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '1820',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '1820',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '496',
        description: 'AUDI Q7 45 TDI QUATTRO TIPTRONIC S LINE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3730',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '3730',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '501',
        description: 'MERCEDES BENZ GLE400D COUPÉ 4MATIC AMG LINE',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '3730',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '3730',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '514',
        description: 'MERCEDES BENZ C220D SEDAN AMG LINE',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '2990',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '2990',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '515',
        description: 'MERCEDES BENZ C220D SEDAN AVANTGARDE',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '2990',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '2990',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '516',
        description: 'MERCEDES BENZ C200 SEDAN AVANTGARDE',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '2990',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '2990',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '521',
        description: 'TOYOTA QUANTUM 2.8 LWB GL 11 SEATER',
        doors: '4',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '1820',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '1820',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '532',
        description: 'MERCEDES BENZ SPRINTER 516CDI',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '4315',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '4315',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Diesel',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
      {
        code: '533',
        description: 'TOYOTA URBAN CRUISER 1.5XS MT',
        doors: '5',
        maxPassengers: null,
        isAvailable: null,
        fee: {
          priceUnit: 'R',
          price: '735',
          feeType: 'Fee Total',
          calculatedDistance: '72',
          calculatedTime: '5400',
        },
        feeBreakdown: {
          fee: [
            {
              priceUnit: 'R',
              price: '735',
              feeType: 'SERVICE CHARGES',
              calculatedDistance: '35',
              calculatedTime: '2600',
            },
          ],
        },
        suitCases: null,
        fuelType: 'Petrol',
        transmissionType: null,
        vehicleExtras: null,
        image: null,
      },
    ],
  },
];
